version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
      - image: mongo:4.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests

############################################################
## Disables Circle CI (Comment/Remove to re-enable CircleCI)
############################################################
workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /.*/